import {
  Conversation,
  Listing,
  Message,
  Reservation,
  User,
} from "./types";

export const CURRENT_USER: User = {
  id: "user-tomek",
  name: "Tomek",
  role: "pasażer",
  location: "Warszawa",
  bio: "Pasjonat lotnictwa. Lubię krótkie loty widokowe i kawę na lotnisku.",
  aviationExperience: "Kilka lotów jako pasażer, podstawy szybowcowe.",
  favoriteAirports: ["EPBC Babice", "EPMO Modlin"],
};

export const MOCK_USERS: User[] = [
  CURRENT_USER,
  {
    id: "user-marek",
    name: "Marek",
    role: "pilot",
    location: "Warszawa",
    bio: "Pilot SEP, latam głównie Cessna 172.",
    aviationExperience: "PPL(A) od 2018, ok. 320h nalotu.",
    favoriteAirports: ["EPBC Babice"],
  },
  {
    id: "user-pawel",
    name: "Paweł",
    role: "pilot",
    location: "Olsztyn",
    bio: "Mazury z lotu ptaka to mój żywioł.",
    favoriteAirports: ["EPKE Kętrzyn"],
  },
  {
    id: "user-adam",
    name: "Adam",
    role: "pilot",
    location: "Warszawa",
    bio: "Lecę często na Wybrzeże, chętnie dzielę miejsce.",
    favoriteAirports: ["EPBC", "EPGD"],
  },
  {
    id: "user-michal",
    name: "Michał",
    role: "szybownik",
    location: "Aeroklub",
    bio: "Szybowce od 10 lat. Pomagam przy startach.",
  },
  {
    id: "user-bartek",
    name: "Bartek",
    role: "skoczek",
    location: "Piotrków Trybunalski",
    bio: "Skoki AFF, ponad 600 skoków.",
  },
  {
    id: "user-marta",
    name: "Marta",
    role: "pasjonat",
    location: "Poznań",
    bio: "Marzy mi się lot widokowy nad Wielkopolską.",
  },
  {
    id: "user-karol",
    name: "Karol",
    role: "organizator",
    location: "Leszno",
    bio: "Organizuję wyjazdy na pikniki lotnicze.",
  },
  {
    id: "user-jarek",
    name: "Jarek",
    role: "pilot",
    location: "Kraków",
    bio: "Latam głównie z Pobiednika. Czasem zabieram pasażerów.",
    favoriteAirports: ["EPKP Pobiednik"],
  },
  {
    id: "user-filip",
    name: "Filip",
    role: "pilot",
    location: "Łódź",
    bio: "Szukam stałego towarzysza nalotów.",
    favoriteAirports: ["EPLL Lublinek"],
  },
  {
    id: "user-ania",
    name: "Ania",
    role: "pomocnik",
    location: "Rzeszów",
    bio: "Pomagam przy organizacji dni otwartych aeroklubu.",
  },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "listing-1",
    authorId: "user-marek",
    authorName: "Marek",
    authorRole: "pilot",
    title: "Robię nalot z EPBC, mam dwa miejsca",
    category: "Robię nalot",
    description:
      "Planuję spokojny lot treningowy w okolicy Warszawy. Mam dwa wolne miejsca dla osób zainteresowanych lotnictwem. Trasa i czas zależne od pogody. Szczegóły ustalimy w wiadomości.",
    activityType: "Lot treningowy SEP",
    startLocation: "Warszawa-Babice",
    startAirport: "EPBC",
    date: "Sobota",
    time: "10:00",
    totalSeats: 3,
    availableSeats: 2,
    costAmount: 220,
    costCurrency: "PLN",
    costType: "orientacyjny udział w kosztach",
    settlementMethod: "gotówka poza aplikacją",
    requirements: "Brak. Wystarczy chęć latania.",
    organizationNotes: "Spotkanie 30 min przed startem przed hangarem.",
    participants: [
      { userId: "user-marek", name: "Marek", role: "autor / pilot", isAuthor: true },
    ],
    participantsVisibility: "tylko imię",
    status: "Aktualne",
  },
  {
    id: "listing-2",
    authorId: "user-pawel",
    authorName: "Paweł",
    authorRole: "pilot",
    title: "Lot widokowy nad Mazurami — jedno wolne miejsce",
    category: "Mam wolne miejsce",
    description:
      "Lot widokowy nad jeziorami mazurskimi. Trasa około godziny w powietrzu. Pogoda będzie zweryfikowana rano.",
    activityType: "Lot widokowy",
    startLocation: "Kętrzyn-Wilamowo",
    startAirport: "EPKE",
    date: "Niedziela",
    time: "12:00",
    totalSeats: 2,
    availableSeats: 1,
    costAmount: 300,
    costCurrency: "PLN",
    costType: "orientacyjny udział w kosztach",
    settlementMethod: "gotówka poza aplikacją",
    participants: [
      { userId: "user-pawel", name: "Paweł", role: "autor / pilot", isAuthor: true },
    ],
    participantsVisibility: "tylko imię",
    status: "Aktualne",
  },
  {
    id: "listing-3",
    authorId: "user-adam",
    authorName: "Adam",
    authorRole: "pilot",
    title: "Lecę z Warszawy do Gdańska, mam jedno miejsce",
    category: "Mam wolne miejsce",
    description:
      "Lot z EPBC do Gdańska. Powrót w niedzielę wieczorem, ale to do indywidualnego ustalenia. Bagaż podręczny.",
    activityType: "Lot transportowy SEP",
    startLocation: "Warszawa",
    startAirport: "EPBC",
    destinationLocation: "Gdańsk",
    destinationAirport: "EPGD",
    date: "Piątek",
    time: "16:30",
    totalSeats: 3,
    availableSeats: 1,
    costAmount: 250,
    costCurrency: "PLN",
    costType: "orientacyjny udział w kosztach",
    settlementMethod: "do ustalenia prywatnie",
    participants: [
      { userId: "user-adam", name: "Adam", role: "autor / pilot", isAuthor: true },
      { userId: "user-x1", name: "Kasia", role: "współuczestniczka" },
    ],
    participantsVisibility: "tylko imię",
    status: "Aktualne",
  },
  {
    id: "listing-4",
    authorId: "user-michal",
    authorName: "Michał",
    authorRole: "szybownik",
    title: "Szukamy osób do pomocy przy szybowcach",
    category: "Szybowce",
    description:
      "Szukamy chętnych do pomocy przy startach szybowców. Świetna okazja, żeby poznać świat szybownictwa od kuchni.",
    activityType: "Pomoc startowa",
    startLocation: "Aeroklub lokalny",
    date: "Sobota",
    time: "08:00",
    totalSeats: 6,
    availableSeats: 4,
    costType: "brak kosztów",
    settlementMethod: "brak rozliczenia",
    organizationNotes: "Wygodne ubranie, krem z filtrem, czapka.",
    participants: [
      { userId: "user-michal", name: "Michał", role: "autor / organizator", isAuthor: true },
      { userId: "user-x2", name: "Ola", role: "pomocnik" },
    ],
    participantsVisibility: "tylko imię",
    status: "Aktualne",
  },
  {
    id: "listing-5",
    authorId: "user-bartek",
    authorName: "Bartek",
    authorRole: "skoczek",
    title: "Grupa na skoki spadochronowe, niedziela rano",
    category: "Skoki spadochronowe",
    description:
      "Wspólny wyjazd grupy znajomych na skoki. Dla osób z licencją lub po AFF. Początkujący po wcześniejszym kontakcie.",
    activityType: "Skoki w grupie",
    startLocation: "Piotrków Trybunalski",
    date: "Niedziela",
    time: "09:00",
    totalSeats: 5,
    availableSeats: 3,
    costType: "koszt do ustalenia",
    settlementMethod: "inne poza aplikacją",
    participants: [
      { userId: "user-bartek", name: "Bartek", role: "autor / organizator", isAuthor: true },
      { userId: "user-x3", name: "Tomek", role: "skoczek" },
    ],
    participantsVisibility: "tylko imię",
    status: "Aktualne",
  },
  {
    id: "listing-6",
    authorId: "user-marta",
    authorName: "Marta",
    authorRole: "pasjonat",
    title: "Szukam możliwości lotu jako pasażer z okolic Poznania",
    category: "Szukam lotu",
    description:
      "Szukam pilota, który zabierze mnie na krótki lot widokowy. Termin elastyczny, mogę dojechać.",
    activityType: "Lot widokowy",
    startLocation: "Poznań i okolice",
    date: "Elastycznie",
    time: "Do ustalenia",
    totalSeats: 1,
    availableSeats: 1,
    costType: "koszt do ustalenia",
    settlementMethod: "do ustalenia prywatnie",
    participants: [
      { userId: "user-marta", name: "Marta", role: "autor / pasażer", isAuthor: true },
    ],
    participantsVisibility: "tylko imię",
    status: "Aktualne",
  },
  {
    id: "listing-7",
    authorId: "user-karol",
    authorName: "Karol",
    authorRole: "organizator",
    title: "Wspólny wypad na piknik lotniczy",
    category: "Wydarzenie lotnicze",
    description:
      "Jedziemy na piknik lotniczy do Leszna. Cały dzień, mnóstwo samolotów, pokazy, gastronomia na miejscu.",
    activityType: "Wyjazd grupowy",
    startLocation: "Leszno",
    date: "Sobota",
    time: "11:00",
    totalSeats: 8,
    availableSeats: 5,
    costType: "brak kosztów",
    settlementMethod: "brak rozliczenia",
    participants: [
      { userId: "user-karol", name: "Karol", role: "autor / organizator", isAuthor: true },
      { userId: "user-x4", name: "Natalia", role: "uczestniczka" },
      { userId: "user-x5", name: "Piotr", role: "uczestnik" },
    ],
    participantsVisibility: "tylko imię",
    status: "Aktualne",
  },
  {
    id: "listing-8",
    authorId: "user-jarek",
    authorName: "Jarek",
    authorRole: "pilot",
    title: "Jadę na lotnisko, mogę zabrać dwie osoby autem",
    category: "Wspólny wyjazd na lotnisko",
    description:
      "Jadę z Krakowa do Pobiednika sobotę rano. Mogę zabrać dwie osoby. Kierunek aeroklub, powrót po południu.",
    activityType: "Wspólny dojazd",
    startLocation: "Kraków",
    destinationLocation: "Pobiednik",
    destinationAirport: "EPKP",
    date: "Sobota",
    time: "07:30",
    totalSeats: 4,
    availableSeats: 2,
    costType: "koszt do ustalenia",
    settlementMethod: "gotówka poza aplikacją",
    participants: [
      { userId: "user-jarek", name: "Jarek", role: "autor / kierowca", isAuthor: true },
    ],
    participantsVisibility: "tylko imię",
    status: "Aktualne",
  },
  {
    id: "listing-9",
    authorId: "user-filip",
    authorName: "Filip",
    authorRole: "pilot",
    title: "Szukam osoby do wspólnego nalotu",
    category: "Szukam współpasażera",
    description:
      "Szukam towarzysza do wspólnego nalotu we wtorek. Krótka trasa, dzielimy koszt równo.",
    activityType: "Nalot wspólny",
    startLocation: "Łódź-Lublinek",
    startAirport: "EPLL",
    date: "Wtorek",
    time: "14:00",
    totalSeats: 2,
    availableSeats: 1,
    costAmount: 200,
    costCurrency: "PLN",
    costType: "podział kosztów",
    settlementMethod: "gotówka poza aplikacją",
    participants: [
      { userId: "user-filip", name: "Filip", role: "autor / pilot", isAuthor: true },
    ],
    participantsVisibility: "tylko imię",
    status: "Aktualne",
  },
  {
    id: "listing-10",
    authorId: "user-ania",
    authorName: "Ania",
    authorRole: "pomocnik",
    title: "Pomoc przy dniu otwartym aeroklubu",
    category: "Potrzebna pomoc na lotnisku",
    description:
      "Aeroklub Rzeszów organizuje dzień otwarty. Potrzebujemy ludzi do pomocy organizacyjnej, info-pointu i przy stoiskach.",
    activityType: "Wolontariat",
    startLocation: "Rzeszów",
    date: "Niedziela",
    time: "09:00",
    totalSeats: 10,
    availableSeats: 6,
    costType: "brak kosztów",
    settlementMethod: "brak rozliczenia",
    organizationNotes: "Posiłek i napoje zapewnione. Wygodne obuwie.",
    participants: [
      { userId: "user-ania", name: "Ania", role: "autor / organizator", isAuthor: true },
      { userId: "user-x6", name: "Wojtek", role: "pomocnik" },
    ],
    participantsVisibility: "tylko imię",
    status: "Aktualne",
  },
];

export const MOCK_RESERVATIONS: Reservation[] = [
  {
    id: "res-1",
    listingId: "listing-2",
    userId: "user-tomek",
    userName: "Tomek",
    seatsRequested: 1,
    message: "Cześć, bardzo chętnie skorzystam, daj znać jeśli pasuje!",
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    listingId: "listing-2",
    listingTitle: "Lot widokowy nad Mazurami — jedno wolne miejsce",
    participantIds: ["user-tomek", "user-pawel"],
    participantNames: ["Tomek", "Paweł"],
  },
  {
    id: "conv-2",
    listingId: "listing-1",
    listingTitle: "Robię nalot z EPBC, mam dwa miejsca",
    participantIds: ["user-tomek", "user-marek"],
    participantNames: ["Tomek", "Marek"],
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "msg-1",
    conversationId: "conv-1",
    senderId: "user-tomek",
    senderName: "Tomek",
    body: "Cześć Paweł, czy miejsce na niedzielę jest jeszcze aktualne?",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 13).toISOString(),
  },
  {
    id: "msg-2",
    conversationId: "conv-1",
    senderId: "user-pawel",
    senderName: "Paweł",
    body: "Cześć! Tak, jest aktualne. Pogoda zapowiada się ok. Zgłoś się przez przycisk na ogłoszeniu, żebym miał to w jednym miejscu.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12.5).toISOString(),
  },
  {
    id: "msg-3",
    conversationId: "conv-2",
    senderId: "user-marek",
    senderName: "Marek",
    body: "Hej, jakbyś chciał dołączyć w sobotę, daj znać.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];
